package firewall

import (
	"strings"
	"testing"
)

// realIPTablesSave is confirmed against real `iptables-save` output shape:
// a *filter section with chain policy lines, INPUT/OUTPUT/FORWARD rules
// (FORWARD must be ignored), a *nat section (must be ignored entirely), and
// a COMMIT line closing each table.
const realIPTablesSave = `# Generated by iptables-save
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -s 192.168.1.0/24 -p tcp -m tcp --dport 80 -j DROP
-A INPUT -i eth0 -p tcp -m tcp --dport 6000:6063 -j ACCEPT
-A INPUT -s 203.0.113.5/32 -j REJECT
-A FORWARD -j DROP
-A OUTPUT -o eth0 -d 10.0.0.1/32 -p udp --dport 53 -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
`

func TestParseIPTablesSave(t *testing.T) {
	rules, err := ParseIPTablesSave(realIPTablesSave)
	if err != nil {
		t.Fatalf("ParseIPTablesSave: %v", err)
	}
	// 4 INPUT rules + 1 OUTPUT rule; FORWARD and the *nat table excluded.
	if len(rules) != 5 {
		t.Fatalf("got %d rules, want 5: %+v", len(rules), rules)
	}

	ssh := rules[0]
	if ssh.Chain != "INPUT" || ssh.Direction != DirectionIn {
		t.Errorf("rule[0] chain/direction = %q/%v, want INPUT/IN", ssh.Chain, ssh.Direction)
	}
	if ssh.Protocol != "tcp" || ssh.PortFrom != 22 || ssh.PortTo != 22 {
		t.Errorf("rule[0] = %+v, want tcp/22", ssh)
	}
	if ssh.Action != ActionAllow {
		t.Errorf("rule[0].Action = %v, want ALLOW", ssh.Action)
	}
	if ssh.Order != 1 {
		t.Errorf("rule[0].Order = %d, want 1", ssh.Order)
	}

	httpDeny := rules[1]
	if httpDeny.Source != "192.168.1.0/24" || httpDeny.PortFrom != 80 || httpDeny.Action != ActionDeny {
		t.Errorf("rule[1] = %+v, want source 192.168.1.0/24, port 80, DENY", httpDeny)
	}

	xrange := rules[2]
	if xrange.Interface != "eth0" || xrange.PortFrom != 6000 || xrange.PortTo != 6063 {
		t.Errorf("rule[2] = %+v, want interface eth0, ports 6000-6063", xrange)
	}

	reject := rules[3]
	if reject.Source != "203.0.113.5" || reject.Action != ActionReject {
		t.Errorf("rule[3] = %+v, want source 203.0.113.5 (no /32 suffix), REJECT", reject)
	}
	if !reject.HasAnyPort() {
		t.Errorf("rule[3] should have no port restriction, got %d-%d", reject.PortFrom, reject.PortTo)
	}
	if reject.Order != 4 {
		t.Errorf("rule[3].Order = %d, want 4 (FORWARD line must not consume an INPUT order slot)", reject.Order)
	}

	dns := rules[4]
	if dns.Chain != "OUTPUT" || dns.Direction != DirectionOut {
		t.Errorf("rule[4] chain/direction = %q/%v, want OUTPUT/OUT", dns.Chain, dns.Direction)
	}
	if dns.Interface != "eth0" || dns.Destination != "10.0.0.1" || dns.PortFrom != 53 {
		t.Errorf("rule[4] = %+v, want interface eth0, destination 10.0.0.1, port 53", dns)
	}
	if dns.Order != 1 {
		t.Errorf("rule[4].Order = %d, want 1 (OUTPUT has its own order sequence)", dns.Order)
	}
}

func TestParseIPTablesPortSpec(t *testing.T) {
	cases := []struct {
		in       string
		wantFrom int
		wantTo   int
		wantErr  bool
	}{
		{"22", 22, 22, false},
		{"6000:6063", 6000, 6063, false},
		{"not-a-port", 0, 0, true},
	}
	for _, c := range cases {
		from, to, err := parseIPTablesPortSpec(c.in)
		if (err != nil) != c.wantErr {
			t.Errorf("parseIPTablesPortSpec(%q) error = %v, wantErr %v", c.in, err, c.wantErr)
			continue
		}
		if err == nil && (from != c.wantFrom || to != c.wantTo) {
			t.Errorf("parseIPTablesPortSpec(%q) = %d, %d; want %d, %d", c.in, from, to, c.wantFrom, c.wantTo)
		}
	}
}

// TestIPTablesAddRuleCommandBuildsTheRealInvocation mirrors
// TestUFWAddRuleCommandBuildsTheRealInvocation for iptables' own
// vocabulary and flag order.
func TestIPTablesAddRuleCommandBuildsTheRealInvocation(t *testing.T) {
	spec := NewRuleSpec{
		Direction: DirectionIn, Action: ActionDeny,
		Protocol: "tcp", PortFrom: 22, PortTo: 22,
		Source: "203.0.113.0/24", Interface: "eth0",
	}
	got, err := IPTablesAddRuleCommand(spec)
	if err != nil {
		t.Fatalf("IPTablesAddRuleCommand: %v", err)
	}
	want := "iptables -A INPUT -p tcp -s 203.0.113.0/24 -i eth0 --dport 22 -j DROP"
	if got != want {
		t.Errorf("IPTablesAddRuleCommand = %q, want %q", got, want)
	}
}

// TestIPTablesAddRuleCommandUsesOutInterfaceFlagForOutgoing pins that
// an Interface on an outbound rule renders as "-o", never "-i" — the
// same direction-dependent flag parseIPTablesRuleFields' own read side
// already assumes (see ParseIPTablesSave's own chain-based Direction).
func TestIPTablesAddRuleCommandUsesOutInterfaceFlagForOutgoing(t *testing.T) {
	spec := NewRuleSpec{Direction: DirectionOut, Interface: "eth0"}
	got, err := IPTablesAddRuleCommand(spec)
	if err != nil {
		t.Fatalf("IPTablesAddRuleCommand: %v", err)
	}
	if !strings.Contains(got, "-o eth0") || strings.Contains(got, "-i eth0") {
		t.Errorf("IPTablesAddRuleCommand = %q, want \"-o eth0\", not \"-i eth0\"", got)
	}
}

// TestIPTablesAddRuleCommandRendersAPortRangeWithAColon pins the one
// place iptables' own port-range notation differs from ufw's (see
// TestUFWAddRuleCommandRendersAPortRangeWithADash).
func TestIPTablesAddRuleCommandRendersAPortRangeWithAColon(t *testing.T) {
	spec := NewRuleSpec{Protocol: "tcp", PortFrom: 6000, PortTo: 6063}
	got, err := IPTablesAddRuleCommand(spec)
	if err != nil {
		t.Fatalf("IPTablesAddRuleCommand: %v", err)
	}
	if !strings.Contains(got, "--dport 6000:6063") {
		t.Errorf("IPTablesAddRuleCommand = %q, want it to contain %q", got, "--dport 6000:6063")
	}
}

// TestIPTablesAddRuleCommandRefusesAPortWithNoProtocol pins a real
// iptables constraint this package would otherwise just hand to a
// shell to fail on with a far less legible error: --dport always
// requires an explicit -p tcp/-p udp naming which protocol it matches
// against first.
func TestIPTablesAddRuleCommandRefusesAPortWithNoProtocol(t *testing.T) {
	spec := NewRuleSpec{PortFrom: 22, PortTo: 22}
	if _, err := IPTablesAddRuleCommand(spec); err == nil {
		t.Error("IPTablesAddRuleCommand should refuse a port with no protocol set")
	}
}

// TestIPTablesDeleteRuleCommandUsesTheDeleteFlag pins the rollback's
// own exact shape: byte-for-byte the same as AddRuleCommand except
// "-D" in place of "-A", never a separately re-derived command line.
func TestIPTablesDeleteRuleCommandUsesTheDeleteFlag(t *testing.T) {
	spec := NewRuleSpec{Direction: DirectionIn, Action: ActionAllow, Protocol: "tcp", PortFrom: 22, PortTo: 22}
	add, err := IPTablesAddRuleCommand(spec)
	if err != nil {
		t.Fatalf("IPTablesAddRuleCommand: %v", err)
	}
	del, err := IPTablesDeleteRuleCommand(spec)
	if err != nil {
		t.Fatalf("IPTablesDeleteRuleCommand: %v", err)
	}
	want := strings.Replace(add, "-A INPUT", "-D INPUT", 1)
	if del != want {
		t.Errorf("IPTablesDeleteRuleCommand = %q, want %q", del, want)
	}
}
